---
name: Prometheus
version: 0.1.6
slug: prometheus
description: Monitoring system & time series database
url: https://github.com/angristan/fork-addon-prometheus
startup: services
ingress: true
ingress_port: 9090
ingress_entry: graph
init: false
panel_icon: mdi:chart-timeline
panel_title: Prometheus
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
homeassistant_api: true
ports:
  9090/tcp: null
ports_description:
  9090/tcp: Not required for Ingress
map:
  - config:rw
options:
  storage_tsdb_retention_time: 15d
schema:
  storage_tsdb_retention_time: str
